version: '3.4'

services:
  web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"
