version: '3.4'

services:
  storage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5102:80"

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"

  riversidecms.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  element.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5103:80"

  cms.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5104:80"
